return {
    START_TRIGGER_DISTANCE = 60,
    SPAWN_INTERVAL = 0.5,
    GLOBAL_AGGRO_INTERVAL = 2.0,
    CHASE_PLAYER_INTERVAL = 4.0,
    WAVE_COMPLETION_CHECK_INTERVAL = 1.0,

    HUD_WAVE_START_REPEAT_DELAY = 2.0,

    CHASE_STOP_DISTANCE = 4.0,
    CHASE_REISSUE_DISTANCE = 6.0,
    DIRECT_CHASE_DISTANCE = 18.0,
    CHASE_MOVEMENT_TYPE = "Sprint",
    CHASE_IGNORE_NAVIGATION = false,

    SEARCH_MOVEMENT_TYPE = "Sprint",
    SEARCH_RADIUS = 5.0,
    SEARCH_LEASH_DISTANCE = 12.0,
    SEARCH_STOP_DISTANCE = 1.5,
    SEARCH_PLAYER_RADIUS = 180.0,
    SEARCH_STEP_DISTANCE = 28.0,
    AUTO_COMBAT_DISTANCE = 18.0,
    COMBAT_JOIN_DISTANCE = 32.0,

    MIN_SPAWN_DISTANCE_FROM_PLAYER = 18.0,
    SPAWN_PUSH_SIDE_SPACING = 4.0,
    SPAWN_RESULT_TIMEOUT = 30.0,
    SPAWN_TRACK_DELAY = 0.15,
    NO_HASH_SPAWN_MATCH_DISTANCE = 120.0,
    SPAWN_POSITION_TOLERANCE = 15.0,
    TELEPORT_CORRECTION_TOLERANCE = 8.0,
    POST_SPAWN_TELEPORT_CORRECTION_DELAYS = { 0.1, 0.35, 0.8 },
    SPAWN_AWARENESS_DELAYS = { 0.45, 0.9, 1.5, 2.5, 4.0, 6.0 },
    MAX_BAD_POSITION_RETRIES = 2,
    MAX_FALLBACK_RETRIES = 1
}
